### PR TITLE
Open in $EDITOR feature.

### PR DESCRIPTION
**Pull request by Plommonsorbet**
If no script arg is entered at command line it will try and open the users EDITOR. Also added subcommand edit for editing an already defined command, only supports editing the script. Would be nice to add the ability to edit the tags, description etc as well.

### CODE REVIEW

**Comment by BenSchZA** [comment]
@Plommonsorbet I like the added feature. There seems to be a merge conflict. Once resolved let's merge.

**Comment by Plommonsorbet** [comment]
@BenSchZA Fixed the merge conflict, however I'm wondering if there's a better way for me to do pull requests.

 I usually do these in coding bursts, so I'll usually just start each new pull request from the current master, so when they get merged they new HEAD doesn't match each branch and which causes merge conflicts. Is there a better way to do this do this or is it just expected that I'll have to fix the pull requests if there's a conflict with another feature?

**Comment by BenSchZA** [comment]
Unfortunately it's expected. If you're working on multiple features at once, all branched off the same commit, you can try only make changes in separate files / functions (ideal), but if not possible then you'll have conflicts.

**Comment by Plommonsorbet** [comment]
Ah okay, that's what I thought as well, I'll just have to deal with it then. :)

**Pull request merged**
