### PR TITLE
ADDED better formatting for commands, by default it now only shows the...

### PR DESCRIPTION
**Pull request by Plommonsorbet**
first line and only 120 characters long.
To show the whole command in the table use the cli option -l.

### CODE REVIEW

**Comment by Plommonsorbet** [comment]
I've arbitrarily just set the max width to 120 because I think that's what a few coding standards use. Does that seem like an okay amount? I guess we could add a config option to change this later.

**Comment by BenSchZA** [comment]
120 characters  is quite long:
```
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```
Maybe 80 characters? Can definitely add a config option later. I like this feature add! I've been using Pier a lot lately.

**Comment by Plommonsorbet** [comment]
I've updated the default to 80 characters, also went ahead and create a cli option and config option for it as well.

Added a few smoke tests for the listing function as well.

**Comment by Plommonsorbet** [comment]
Accidentally pushed to this branch again while working on some code refactoring. Reverted it back to the correct version. This pull request is ready to be added.

**Pull request closed without merging**
