### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by Plommonsorbet**
Hey!

Thought I would do some more code cleanup and reorganizing, also updated the help text and some other small things like adding aliases to the subcommands, like ls for list and rm for remove.

I also changed from clap to structopt as it makes the commandline options a lot more structured.

/Isak

### CODE REVIEW

**Comment by BenSchZA** [comment]
These changes make a number of things a lot cleaner! Awesome work. Do you mind removing my email from the README? Otherwise looks good to go.

**Comment by BenSchZA** [comment]
Let's get this merged in first before your other PR to avoid conflicts, I see you branched off this feature branch.

**Comment by BenSchZA** [comment]
There are a number of feature branches that have been merged in but still exist - makes the git tree a bit messy, might be worth deleting them.

**Comment by Plommonsorbet** [comment]
> These changes make a number of things a lot cleaner! Awesome work. Do you mind removing my email from the README? Otherwise looks good to go.

It comes from the authors section of the cargo.toml file, I can remove it from there. When updating the the README I usually just do this via vim with this command `read ! target/debug/pier --help`, so whatever is in the help will end up in the README.

Yeah the git history is a bit messy I'll rebase it and resubmit it. I have a lot to learn about that still but it's a nice challenge.

**Comment by BenSchZA** [comment]
Ah okay. I don't know that's it's necessary to have an email in the CLI, so happy that we remove it from there too. Let's do it on this branch so it doesn't get merged into README.

Re. the git history, no rebase necessary - referring to the remote branches on your fork - for now I'm just hiding your remote when working with git tree, but not serious :)

**Comment by Plommonsorbet** [comment]
I was playing around with rebasing it and was able to get it completely clean, but I still have to do a merge once doing the pull request to the master. I think if we would want it cleaner you would have to do the rebas on the master branch and then force push it. But I guess that's a pretty minor thing though and can be done later.

Removed the email adress as well.

**Comment by BenSchZA** [comment]
Great! Happy to merge this now. (re. the rebase, I think you're misunderstanding me, don't worry about it :) )

**Pull request merged**
